version: '3'
services: 
        db:
                image: redis:latest
                ports: 
                        - '6380:6379'
        app:
                build: . 
                ports:
                        - '9292:9292'
                volumes:
                        - .:/mockup
                links:
                        - db
                env_file: .env

